version: '1'
services:
  back:
    image: nabilchebili/tkt:latest
    ports:
      - "8080:5000"
    environment:
      ENVIRONMENT: 'world'
    volumes:
      - appli:/app/logs/
  front:
    image: nabilchebili/front:latest
    ports:
      - "9000:80" 
    environment:
      WS_BACK_URL: 'http://localhost:8080'
volumes:
  appli:
    external: true
