apiVersion: v1
kind: Service # Specify the kind of resource to create. Here we want to create a Service object
metadata:
  labels:
    app: back # Specify a label for this service object
  name: back # Specify a name for this service object
spec:
  # <=============== You must fill this part ==================>
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer: {}
