# Fill this frontend deployment manifest
apiVersion: apps/v1
kind: Deployment # Specify the kind of resource to create. Here we want to create a Deployment object
metadata:
  labels:
    app: front # Specify a label for this deployment object
  name: front # Specify a name for this deployment object
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: front # Allow this deployment to control pods labelled with `app: front`
  template: # Specify template for each created pods
    metadata:
      labels:
        app: front # Allow created pods to be selected by deployment with matchLabels
    spec: 
      # <=============== You must fill this part ==================>
      restartPolicy: Always
      containers:
      - name: front
        image: nabilchebili/frontprojet:latest
        env:
        - name: API_SERVICE_URL
          value: http://40.114.175.240:3000
        ports:
        - containerPort: 3000